services:
  db:
    image: postgres:16
    container_name: cafe_fausse_db
    environment:
      POSTGRES_DB: cafe_fausse
      POSTGRES_USER: cafe
      POSTGRES_PASSWORD: cafe_password
    ports:
      - "5432:5432"
    volumes:
      - cafe_fausse_pgdata:/var/lib/postgresql/data

volumes:
  cafe_fausse_pgdata:
